# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_discussion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Discussion'),
        ),
    ]
