# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20160414_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='active',
        ),
    ]
