# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cwid',
            field=models.IntegerField(blank=True),
        ),
    ]
