# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0003_auto_20160412_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Student',
        ),
    ]
