# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_accounts', '0004_auto_20160418_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='MyUser',
        ),
    ]
