# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_activities', '0003_auto_20160418_2207'),
        ('course_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_activities.Activity'),
        ),
    ]
