# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assignment', '0003_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='content',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='course_activity',
            new_name='grade_item',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='path',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='title',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='update',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
