# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assignment', '0004_auto_20160426_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course_assignment',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assignment.Assignment'),
        ),
    ]
