# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160409_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=19, max_length=4),
        ),
    ]
