# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_semester_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=19),
        ),
    ]
