# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160410_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(to='courses.Semester'),
        ),
    ]
