# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True),
        ),
    ]
