# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20160412_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enrolled',
            new_name='current_enrolled',
        ),
    ]
