# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20160412_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='semester',
            name='registered_course',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course'),
        ),
    ]
