# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160412_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='registered_course',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
