# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20160412_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='registered_course',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester'),
        ),
    ]
