# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20160412_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='slug',
        ),
    ]
