# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_semester_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('slug', 'semester')]),
        ),
    ]
