# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20160415_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='course',
            name='update',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='update',
        ),
    ]
