# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20160415_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='is_active',
            new_name='active',
        ),
    ]
